<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <RootNamespace>Qasid.Browser</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Qasid.Core\Qasid.Core.csproj" />
    </ItemGroup>
</Project>
